### ISSUE TITLE
TOW fitting functions--where are they?

### ISSUE THREAD

**Issue by jwoodward0** [kW-Labs/nmecr#12] opened 2022-07-27 14:38 UTC
Hi. Amazing resource here. Contrary to what the README says, I can't find any code a fits a Time of Week model (ignoring temperature). Do I need to wear glasses ; ) 

Any guidance is much appreciated. Please and Thank You.
jrw

**Comment by dexterluu** [comment] 2022-07-27 18:31
Hi,

Thanks for using the package and bringing it to our attention that it's not really clear how to use the Time of Week model. Using the model_with_TOWT function, there's an argument named model_input_options which should be a list. One of the fields in that list is regression_type and that should be set to "TOW" when trying to run the Time of Week model.

**Comment by dexterluu** [comment] 2022-08-18 20:42
Assuming the issue is resolved. Closing.

**Closed by dexterluu** 2022-08-18 20:42 UTC
