### ISSUE TITLE
Infinite loop fitting 5P Change Model

### ISSUE THREAD

**Issue by LucaNicoliYT88** [kW-Labs/nmecr#11] opened 2022-02-10 10:22 UTC
**Describe the bug**
When a 3PH model failed on a load curve, I had the following error ‘A 3PH model could not be computed. No breakpoint found’ and the object returned is a ‘NULL’ string.
I can easily catch this checking the NULL string.

When the 5P model goes in loop, it is not able to end the process. The string ‘breakpoint estimate(s): 48.80786 76.08952’ is repeated and the process does not end. I need to kill manually. Is it possible to insert a max number of retries?

**To Reproduce**
Pass script and data

**Expected behavior**
Is it possible to insert a max number of retries and end the process?
[example_baseline_modified.zip](https://github.com/kW-Labs/nmecr/files/8040177/example_baseline_modified.zip)

**Comment by DrDAJump** [comment] 2022-03-28 18:36
update segement package?

**Comment by LucaNicoliYT88** [comment] 2022-04-12 09:35
what do you mean?

**Comment by dexterluu** [comment] 2022-06-30 16:47
I tried reproducing your error with the data and script you provided but I wasn't getting the exact issue. During the model_with_CP step, the 5P model would not be able to find a breakpoint and would send back a warning because of that. It would then error out almost instantly when checking an IF statement because the criteria was checking against an NA value caused when the 5P model couldn't converge to breakpoints. If possible, could you provide more details to help me reproduce the issue?

**Comment by dexterluu** [comment] 2022-08-18 20:41
Closing issue because I think the most recent release addresses the issue. It seemed to be due to a breakpoint temperature being too close to the outer temperature limits.

**Closed by dexterluu** 2022-08-18 20:41 UTC
